[2017-12-13 22:31:35,659] launcher  INFO    SCOOP 0.7 1.1 on linux2 using Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4], API: 1013
[2017-12-13 22:31:35,659] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2017-12-13 22:31:35,659] launcher  INFO    Worker distribution: 
[2017-12-13 22:31:35,659] launcher  INFO       127.0.0.1:	3 + origin
2017-12-13 22:31:35,876 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:35,876 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:35,877 root            INFO     Loading data (./data/cran_historical_10_12)
2017-12-13 22:31:35,886 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:35,886 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:35,886 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
2017-12-13 22:31:35,897 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:35,897 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:35,897 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
[2017-12-13 22:31:35,934] launcher  (127.0.0.1:33373) INFO    Root process is done.
[2017-12-13 22:31:35,934] launcher  (127.0.0.1:33373) INFO    Finished cleaning spawned subprocesses.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
[2017-12-13 22:31:36,174] launcher  INFO    SCOOP 0.7 1.1 on linux2 using Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4], API: 1013
[2017-12-13 22:31:36,174] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2017-12-13 22:31:36,174] launcher  INFO    Worker distribution: 
[2017-12-13 22:31:36,174] launcher  INFO       127.0.0.1:	3 + origin
2017-12-13 22:31:36,387 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:36,387 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:36,388 root            INFO     Loading data (./data/cran_historical_10_12)
2017-12-13 22:31:36,393 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:36,394 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:36,394 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
2017-12-13 22:31:36,422 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:36,423 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:36,423 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
2017-12-13 22:31:36,477 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:36,477 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:36,478 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
[2017-12-13 22:31:36,514] launcher  (127.0.0.1:46575) INFO    Root process is done.
[2017-12-13 22:31:36,514] launcher  (127.0.0.1:46575) INFO    Finished cleaning spawned subprocesses.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
[2017-12-13 22:31:36,760] launcher  INFO    SCOOP 0.7 1.1 on linux2 using Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4], API: 1013
[2017-12-13 22:31:36,760] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2017-12-13 22:31:36,760] launcher  INFO    Worker distribution: 
[2017-12-13 22:31:36,760] launcher  INFO       127.0.0.1:	3 + origin
2017-12-13 22:31:36,977 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:36,977 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:36,978 root            INFO     Loading data (./data/cran_historical_10_12)
2017-12-13 22:31:36,986 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:36,987 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:36,987 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
2017-12-13 22:31:37,054 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:37,055 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:37,055 root            INFO     Loading data (./data/cran_historical_10_12)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 302, in <module>
    b.main()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 257, in run
    globs.update(self.setupEnvironment(self))
  File "/usr/local/lib/python2.7/dist-packages/scoop/bootstrap/__main__.py", line 210, in setupEnvironment
    scoop.MAIN_MODULE,
  File "./genoptesn.py", line 62, in <module>
    X, Y = esnet.load_from_text(args.data)
  File "esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
2017-12-13 22:31:37,079 parameterhelper INFO     Loading config for dimensionality as a percentage of the reservoir size.
2017-12-13 22:31:37,079 parameterhelper INFO     Config: ./configs/user/enet_identity (overload)
2017-12-13 22:31:37,080 root            INFO     Loading data (./data/cran_historical_10_12)
[2017-12-13 22:31:37,095] launcher  (127.0.0.1:53706) INFO    Root process is done.
[2017-12-13 22:31:37,096] launcher  (127.0.0.1:53706) INFO    Finished cleaning spawned subprocesses.
Traceback (most recent call last):
  File "./esn_run.py", line 123, in <module>
    main()
  File "./esn_run.py", line 88, in main
    X, Y = esnet.load_from_text(args.data)
  File "/home/minh/PycharmProjects/Ensemble/PythonESN/esnet.py", line 427, in load_from_text
    return np.atleast_2d(data[:, [0,1,2,3,4,5,6,7,8,9]]), np.atleast_2d(data[:, 10]).T
IndexError: index 6 is out of bounds for axis 1 with size 6
